codecov:
  require_ci_to_pass: true
  notify:
    after_n_builds: 1

coverage:
  status:
    project:
      default:
        target: 95%
        threshold: 0.5%
        base: auto
        flags:
          - api
    patch:
      default:
        target: 95%
        threshold: 0.5%
        base: auto

ignore:
  - "ui/**"
  - "bench/**"
  - "**/tests/**"
  - "**/__pycache__/**"
  - "**/*.md"

flag_management:
  default_rules:
    carryforward: true
  individual_flags:
    - name: api
      paths:
        - api/
