name: API tests and coverage (gate 95)

on:
  pull_request:
    paths:
      - 'api/**'
      - '.github/workflows/api-tests.yml'
  push:
    branches: [ develop, main ]
    paths:
      - 'api/**'
      - '.github/workflows/api-tests.yml'

jobs:
  test-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            api/pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Lint (Ruff)
        run: |
          ruff version
          ruff check .

      - name: Run tests with coverage
        run: |
          coverage run -m pytest

      - name: Coverage report (enforce 95%)
        run: |
          coverage report --fail-under=95

      - name: Build HTML coverage report
        if: always()
        run: |
          coverage html

      - name: Upload coverage HTML artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: api/coverage_html
          if-no-files-found: warn
