name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  api:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('api/pyproject.toml') }}
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[dev]
      - name: Lint
        run: |
          python -m ruff check
      - name: Test with coverage (95% gate)
        run: |
          python -m pytest --cov --cov-fail-under=95 --cov-report=term-missing --cov-report=xml:coverage.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: api/coverage.xml
          flags: api
          fail_ci_if_error: false
          verbose: true

  ui:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ui/package.json
      - name: Install
        run: npm ci || npm i
      - name: Test with coverage
        run: npm run test:coverage
      - name: Upload UI coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          directory: ui
          flags: ui
          fail_ci_if_error: false
          verbose: true
 
