name: Release Images

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract tag
        id: meta
        run: |
          ref="${GITHUB_REF##*/}"
          echo "tag=${ref}" >> $GITHUB_OUTPUT
          echo "sha=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push API
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile.api
          platforms: linux/amd64
          push: true
          provenance: true
          sbom: true
          tags: |
            ghcr.io/${{ github.repository }}/api:${{ steps.meta.outputs.tag }}
            ghcr.io/${{ github.repository }}/api:sha-${{ steps.meta.outputs.sha }}

      - name: Build and push UI
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile.ui
          platforms: linux/amd64
          push: true
          provenance: true
          sbom: true
          tags: |
            ghcr.io/${{ github.repository }}/ui:${{ steps.meta.outputs.tag }}
            ghcr.io/${{ github.repository }}/ui:sha-${{ steps.meta.outputs.sha }}

      - name: Scan API image with Trivy
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ghcr.io/${{ github.repository }}/api:${{ steps.meta.outputs.tag }}
          format: sarif
          output: trivy-api.sarif
          severity: CRITICAL,HIGH

      - name: Scan UI image with Trivy
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ghcr.io/${{ github.repository }}/ui:${{ steps.meta.outputs.tag }}
          format: sarif
          output: trivy-ui.sarif
          severity: CRITICAL,HIGH

      - name: Upload Trivy results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-api.sarif

      - name: Upload Trivy results (UI)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-ui.sarif
